name: deploy
on:
  push:
    branches:
      - main

jobs:
  preview-deploy:
    name: Deploy Preview
    runs-on: ubuntu-latest
    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: (cd frontend && yarn install --frozen-lockfile && yarn cloud)
#      - run: npx cloud test
      - run: yarn deploy:preview
#  preview-e2e:
#    needs: preview-deploy
#    name: E2E Tests Preview
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      # Install NPM dependencies, cache them correctly
#      # and run all Cypress tests
#      - name: Cypress run
#        uses: cypress-io/github-action@v2
#        with:
#          working-directory: ./cypress
#          record: true
#        env:
#          # pass the Dashboard record key as an environment variable
#          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
#          # pass GitHub token to allow accurately detecting a build vs a re-run build
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          CYPRESS_BASE_URL: 'https://polished-silence-swjqe.cloud.serverless.com'
  production-deploy:
#    needs: preview-e2e
    needs: preview-deploy
    name: Deploy Production
    runs-on: ubuntu-latest
    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn promote:production
#  production-e2e:
#    needs: production-deploy
#    name: E2E Tests Prod
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      # Install NPM dependencies, cache them correctly
#      # and run all Cypress tests
#      - name: Cypress run
#        uses: cypress-io/github-action@v2
#        with:
#          working-directory: ./cypress
#          record: true
#        env:
#          # pass the Dashboard record key as an environment variable
#          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
#          # pass GitHub token to allow accurately detecting a build vs a re-run build
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          CYPRESS_BASE_URL: 'https://raspy-heart-silnh.cloud.serverless.com'